project:
  type: manuscript

manuscript:
  article: report.qmd

format:
  html:
    code-fold: true
  docx: default
  pdf:
    notebook-links: false
    fontsize: 10pt
    geometry:
      - margin=0.7in
    include-in-header:
      text: |
        \usepackage{titlesec}
        \usepackage{enumitem}
        \titlespacing*{\section}{0pt}{1.0ex plus 0.2ex minus .2ex}{0.6ex plus .1ex}
        \titlespacing*{\subsection}{0pt}{0.8ex plus 0.2ex minus .2ex}{0.5ex plus .1ex}
        \titleformat{\section}{\normalfont\large\bfseries}{\thesection}{0.5em}{}
        \titleformat{\subsection}{\normalfont\normalsize\bfseries}{\thesubsection}{0.5em}{}
        \titleformat{\subsubsection}{\normalfont\normalsize\bfseries\itshape}{\thesubsubsection}{0.5em}{}
        \titlespacing*{\subsubsection}{0pt}{0.7ex plus 0.2ex minus .2ex}{0.4ex plus .1ex}
        \setkomafont{title}{\normalfont\Large\bfseries}
        \setkomafont{author}{\normalfont\small}
        \setlist{itemsep=0pt, topsep=2pt, parsep=0pt}
        \setlength{\parskip}{2pt plus 1pt minus 1pt}
        \setlength{\abovecaptionskip}{2pt}
        \setlength{\belowcaptionskip}{2pt}
        \setlength{\textfloatsep}{6pt plus 2pt minus 2pt}
        \setlength{\intextsep}{6pt plus 2pt minus 2pt}

execute:
  freeze: auto
  echo: false
