{
  "hash": "776d96ba75e5c081f59d221256cbc9fe",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: A physics-aware recurrent surrogate for nonlinear viscoelastic tendon force prediction\nauthor:\n  name: Hudson Burke\n  affiliations:\n  - University of Virginia\n  - Mechanical and Aerospace Engineering\nbibliography: references.bib\njupyter: python3\n---\n\n::: {.cell execution_count=1}\n``` {.python .cell-code .hidden}\nimport csv\nimport json\nimport os\nimport shutil\nimport sys\nimport time\nfrom collections import defaultdict\nfrom pathlib import Path\n\nimport matplotlib.pyplot as plt\nfrom matplotlib.patches import FancyArrowPatch, FancyBboxPatch\nimport numpy as np\nimport pyarrow.parquet as pq\nimport torch\n\nROOT = Path('.')\nSRC = ROOT / 'src'\nif str(SRC) not in sys.path:\n    sys.path.insert(0, str(SRC))\n\nFORCE_RETRAIN = os.getenv('PADL_FORCE_RETRAIN', '').strip().lower() in {'1', 'true', 'yes', 'y'}\n\nfrom tendon_surrogate.config import load_config\nfrom tendon_surrogate.data import compute_normalization_stats, load_sequence_records, make_dataloader, split_records\nfrom tendon_surrogate.diagnostics import generate_prediction_diagnostics\nfrom tendon_surrogate.training import evaluate_checkpoint, run_training\n\n\ndef load_json(path):\n    return json.loads(Path(path).read_text())\n\n\ndef load_csv_rows(path):\n    with Path(path).open(newline='') as f:\n        return list(csv.DictReader(f))\n\n\ndef load_prediction_series(path):\n    rows = load_csv_rows(path)\n    grouped = defaultdict(list)\n    for row in rows:\n        grouped[row['sim_id']].append(row)\n    out = {}\n    for sim_id, sim_rows in grouped.items():\n        sim_rows = sorted(sim_rows, key=lambda r: float(r['time']))\n        out[sim_id] = {\n            'split': sim_rows[0]['split'],\n            'time': np.array([float(r['time']) for r in sim_rows]),\n            'force_true': np.array([float(r['force_true']) for r in sim_rows]),\n            'force_pred': np.array([float(r['force_pred']) for r in sim_rows]),\n            'force_abs_err': np.array([float(r['force_abs_err']) for r in sim_rows]),\n        }\n    return out\n\n\ndef make_markdown_table(headers, rows):\n    lines = [\n        '| ' + ' | '.join(headers) + ' |',\n        '| ' + ' | '.join(['---'] * len(headers)) + ' |',\n    ]\n    for row in rows:\n        lines.append('| ' + ' | '.join(str(x) for x in row) + ' |')\n    return '\\n'.join(lines)\n\n\ndef select_best_and_worst(metric_rows, split):\n    subset = sorted([r for r in metric_rows if r['split'] == split], key=lambda r: float(r['mae']))\n    return subset[0], subset[-1]\n\n\ndef metric_lookup(metric_rows):\n    return {row['sim_id']: row for row in metric_rows}\n\n\ndef physical_summary(metric_rows, series_map, split):\n    metric_subset = [r for r in metric_rows if r['split'] == split]\n    series_subset = [series for series in series_map.values() if series['split'] == split]\n    true_rel = [\n        (float(r['peak_true']) - float(r['final_true'])) / max(float(r['peak_true']), 1e-12)\n        for r in metric_subset\n    ]\n    pred_rel = [\n        (float(r['peak_pred']) - float(r['final_pred'])) / max(float(r['peak_pred']), 1e-12)\n        for r in metric_subset\n    ]\n    relax_err = [abs(a - b) for a, b in zip(true_rel, pred_rel)]\n    t0_pred = [float(series['force_pred'][0]) for series in series_subset]\n    peak_bias = [float(r['peak_pred']) - float(r['peak_true']) for r in metric_subset]\n    final_bias = [float(r['final_pred']) - float(r['final_true']) for r in metric_subset]\n    return {\n        'mean_t0_pred': float(np.mean(t0_pred)),\n        'mean_true_relax': float(np.mean(true_rel)),\n        'mean_pred_relax': float(np.mean(pred_rel)),\n        'mean_abs_relax_err': float(np.mean(relax_err)),\n        'mean_peak_bias': float(np.mean(peak_bias)),\n        'mean_final_bias': float(np.mean(final_bias)),\n    }\n\n\ndef plot_model_metric_comparison(baseline_interp, physics_interp, baseline_holdout, physics_holdout):\n    groups = ['Interp val', 'Interp test', 'Holdout val', 'Holdout test']\n    baseline_mae = [\n        baseline_interp['metrics']['val']['mae'],\n        baseline_interp['metrics']['test']['mae'],\n        baseline_holdout['metrics']['val']['mae'],\n        baseline_holdout['metrics']['test']['mae'],\n    ]\n    physics_mae = [\n        physics_interp['metrics']['val']['mae'],\n        physics_interp['metrics']['test']['mae'],\n        physics_holdout['metrics']['val']['mae'],\n        physics_holdout['metrics']['test']['mae'],\n    ]\n    baseline_mse = [\n        baseline_interp['metrics']['val']['mse'],\n        baseline_interp['metrics']['test']['mse'],\n        baseline_holdout['metrics']['val']['mse'],\n        baseline_holdout['metrics']['test']['mse'],\n    ]\n    physics_mse = [\n        physics_interp['metrics']['val']['mse'],\n        physics_interp['metrics']['test']['mse'],\n        physics_holdout['metrics']['val']['mse'],\n        physics_holdout['metrics']['test']['mse'],\n    ]\n\n    x = np.arange(len(groups))\n    width = 0.35\n    fig, axes = plt.subplots(1, 2, figsize=(10, 4.3))\n\n    axes[0].bar(x - width / 2, baseline_mae, width, label='GRU baseline')\n    axes[0].bar(x + width / 2, physics_mae, width, label='Explicit Maxwell model')\n    axes[0].set_xticks(x)\n    axes[0].set_xticklabels(groups, rotation=20)\n    axes[0].set_ylabel('MAE')\n    axes[0].grid(True, axis='y', alpha=0.3)\n    axes[0].legend(loc='upper left')\n\n    axes[1].bar(x - width / 2, baseline_mse, width, label='GRU baseline')\n    axes[1].bar(x + width / 2, physics_mse, width, label='Explicit Maxwell model')\n    axes[1].set_xticks(x)\n    axes[1].set_xticklabels(groups, rotation=20)\n    axes[1].set_ylabel('MSE')\n    axes[1].set_yscale('log')\n    axes[1].grid(True, axis='y', alpha=0.3)\n\n    fig.tight_layout()\n\n\ndef plot_diagnostic_pair(metric_rows, series_map, split, title_prefix, model_label):\n    best_row, worst_row = select_best_and_worst(metric_rows, split)\n    cases = [('Best', best_row), ('Worst', worst_row)]\n\n    fig, axes = plt.subplots(2, 2, figsize=(9, 5.6), sharex='col', height_ratios=[3, 1.4])\n\n    for col, (label, row) in enumerate(cases):\n        sim_id = row['sim_id']\n        series = series_map[sim_id]\n\n        axes[0, col].plot(series['time'], series['force_true'], linewidth=2, label='true force')\n        axes[0, col].plot(series['time'], series['force_pred'], linewidth=2, linestyle='--', label=model_label)\n        axes[0, col].set_title(\n            f\"{label}: {sim_id}\\nMAE={float(row['mae']):.4f}, RMSE={float(row['rmse']):.4f}\"\n        )\n        axes[0, col].set_ylabel('Force')\n        axes[0, col].grid(True, alpha=0.3)\n\n        axes[1, col].plot(series['time'], series['force_abs_err'], color='tab:red', linewidth=1.8)\n        axes[1, col].set_xlabel('Time')\n        axes[1, col].set_ylabel('|error|')\n        axes[1, col].grid(True, alpha=0.3)\n        axes[1, col].text(\n            0.01,\n            0.95,\n            (\n                f\"tendon_l1={float(row['tendon_l1']):g}, visco_g1={float(row['visco_g1']):.2g}, \"\n                f\"visco_t1={float(row['visco_t1']):.2g}, ramp_time={float(row['ramp_time']):.2g}\"\n            ),\n            transform=axes[1, col].transAxes,\n            va='top',\n            ha='left',\n            fontsize=9,\n        )\n\n    axes[0, 0].legend(loc='upper right')\n    fig.suptitle(title_prefix)\n    fig.tight_layout()\n\n\ndef plot_case_comparison(sim_ids, baseline_series, physics_series, baseline_lookup, physics_lookup, title_prefix):\n    fig, axes = plt.subplots(2, len(sim_ids), figsize=(9.5, 5.8), sharex='col', height_ratios=[3, 1.4])\n    if len(sim_ids) == 1:\n        axes = np.array([[axes[0]], [axes[1]]])\n\n    for col, sim_id in enumerate(sim_ids):\n        true_series = physics_series[sim_id]\n        baseline_pred = baseline_series[sim_id]\n        physics_pred = physics_series[sim_id]\n        baseline_row = baseline_lookup[sim_id]\n        physics_row = physics_lookup[sim_id]\n\n        axes[0, col].plot(true_series['time'], true_series['force_true'], linewidth=2, label='true force')\n        axes[0, col].plot(true_series['time'], baseline_pred['force_pred'], linewidth=2, linestyle='--', label='GRU baseline')\n        axes[0, col].plot(true_series['time'], physics_pred['force_pred'], linewidth=2, linestyle='-.', label='Explicit Maxwell')\n        axes[0, col].set_title(\n            f\"{sim_id}\\nGRU MAE={float(baseline_row['mae']):.4f}, Explicit Maxwell MAE={float(physics_row['mae']):.4f}\"\n        )\n        axes[0, col].set_ylabel('Force')\n        axes[0, col].grid(True, alpha=0.3)\n\n        axes[1, col].plot(true_series['time'], baseline_pred['force_abs_err'], linewidth=1.8, label='GRU |error|')\n        axes[1, col].plot(true_series['time'], physics_pred['force_abs_err'], linewidth=1.8, label='Explicit Maxwell |error|')\n        axes[1, col].set_xlabel('Time')\n        axes[1, col].set_ylabel('|error|')\n        axes[1, col].grid(True, alpha=0.3)\n        axes[1, col].text(\n            0.01,\n            0.95,\n            (\n                f\"tendon_l1={float(physics_row['tendon_l1']):g}, visco_g1={float(physics_row['visco_g1']):.2g}, \"\n                f\"visco_t1={float(physics_row['visco_t1']):.2g}, ramp_time={float(physics_row['ramp_time']):.2g}\"\n            ),\n            transform=axes[1, col].transAxes,\n            va='top',\n            ha='left',\n            fontsize=9,\n        )\n\n    axes[0, 0].legend(loc='upper right')\n    axes[1, 0].legend(loc='upper right')\n    fig.suptitle(title_prefix)\n    fig.tight_layout()\n\n\ndef plot_dataset_trajectories(dataset_path):\n    table = pq.read_table(dataset_path)\n    rows = table.to_pylist()\n    grouped = defaultdict(list)\n    for row in rows:\n        grouped[str(row['sim_id'])].append(row)\n\n    by_stiffness = defaultdict(list)\n    for sim_id, sim_rows in grouped.items():\n        sim_rows = sorted(sim_rows, key=lambda r: float(r['time']))\n        stiffness = float(sim_rows[0]['tendon_l1'])\n        t = np.array([float(r['time']) for r in sim_rows])\n        f = np.array([float(r['force']) for r in sim_rows])\n        by_stiffness[stiffness].append((t, f))\n\n    stiffness_levels = sorted(by_stiffness)\n    fig, axes = plt.subplots(1, 4, figsize=(10.2, 2.6), sharex=True, sharey=True)\n\n    for ax, stiffness in zip(axes, stiffness_levels, strict=False):\n        curves = by_stiffness[stiffness]\n        for t, f in curves:\n            ax.plot(t, f, color='tab:blue', alpha=0.16, linewidth=0.9)\n        ax.set_title(f'l1 = {stiffness:g}\\n(n={len(curves)})', fontsize=9)\n        ax.grid(True, alpha=0.25)\n        ax.tick_params(labelsize=8)\n\n    axes[0].set_ylabel('Force', fontsize=9)\n    for ax in axes:\n        ax.set_xlabel('Time', fontsize=9)\n    fig.tight_layout()\n    return fig\n\n\ndef benchmark_model(checkpoint_path, config_path, split='test', batch_size=16, n_warmup=3, n_runs=20):\n    cfg = load_config(ROOT / config_path)\n    records = load_sequence_records(\n        ROOT / cfg.data.dataset_path,\n        sim_id_col=cfg.data.sim_id_col,\n        split_col=cfg.data.split_col,\n        time_col=cfg.data.time_col,\n        dynamic_features=cfg.data.dynamic_features,\n        static_features=cfg.data.static_features,\n        target_col=cfg.data.target,\n    )\n    split_map = split_records(records)\n    stats = compute_normalization_stats(\n        split_map['train'],\n        dynamic_features=cfg.data.dynamic_features,\n        static_features=cfg.data.static_features,\n        target_col=cfg.data.target,\n    )\n    loader = make_dataloader(\n        split_map[split],\n        stats,\n        batch_size=min(batch_size, len(split_map[split])),\n        shuffle=False,\n        num_workers=0,\n    )\n    batch = next(iter(loader))\n    batch = {k: (v.to('cpu') if torch.is_tensor(v) else v) for k, v in batch.items()}\n\n    model = cfg.model.build(cfg.data).to('cpu')\n    checkpoint = torch.load(ROOT / checkpoint_path, map_location='cpu', weights_only=False)\n    model.load_state_dict(checkpoint['model_state'])\n    model.eval()\n\n    n_params = sum(p.numel() for p in model.parameters())\n    with torch.no_grad():\n        for _ in range(n_warmup):\n            model(batch['dynamic'], batch['static'], batch['dynamic_raw'], batch.get('static_raw'))\n        start = time.perf_counter()\n        for _ in range(n_runs):\n            model(batch['dynamic'], batch['static'], batch['dynamic_raw'], batch.get('static_raw'))\n        elapsed = time.perf_counter() - start\n\n    batch_n = int(batch['dynamic'].shape[0])\n    return {\n        'n_params': int(n_params),\n        'ms_per_batch': 1000.0 * elapsed / n_runs,\n        'ms_per_sim': 1000.0 * elapsed / n_runs / batch_n,\n        'batch_size': batch_n,\n    }\n\n\ndef plot_final_model_architecture():\n    fig, axes = plt.subplots(1, 2, figsize=(11.6, 5.2), gridspec_kw={'width_ratios': [1.08, 1.0]})\n    ax1, ax2 = axes\n\n    for ax in axes:\n        ax.set_xlim(0, 1)\n        ax.set_ylim(0, 1)\n        ax.axis('off')\n\n    def box(ax, x, y, w, h, text, fc='#f5f7fb', ec='#2f4b7c', fontsize=10, weight='normal'):\n        patch = FancyBboxPatch(\n            (x, y), w, h,\n            boxstyle='round,pad=0.015,rounding_size=0.02',\n            linewidth=1.5,\n            edgecolor=ec,\n            facecolor=fc,\n        )\n        ax.add_patch(patch)\n        ax.text(\n            x + w / 2,\n            y + h / 2,\n            text,\n            ha='center',\n            va='center',\n            fontsize=fontsize,\n            weight=weight,\n            wrap=True,\n        )\n        return (x, y, w, h)\n\n    def anchor(rect, side='right', frac=0.5):\n        x, y, w, h = rect\n        if side == 'right':\n            return (x + w, y + frac * h)\n        if side == 'left':\n            return (x, y + frac * h)\n        if side == 'top':\n            return (x + frac * w, y + h)\n        if side == 'bottom':\n            return (x + frac * w, y)\n        raise ValueError(f'Unknown side: {side}')\n\n    def arrow(ax, a, b, start='right', end='left', start_frac=0.5, end_frac=0.5, rad=0.0):\n        p1 = anchor(a, start, start_frac)\n        p2 = anchor(b, end, end_frac)\n        arr = FancyArrowPatch(\n            p1,\n            p2,\n            arrowstyle='->',\n            mutation_scale=12,\n            linewidth=1.4,\n            color='#333333',\n            connectionstyle=f'arc3,rad={rad}',\n        )\n        ax.add_patch(arr)\n\n    fig.suptitle(\n        'Final physics-aware model: coupled Maxwell surrogate with explicit tendon scaling',\n        fontsize=9,\n        weight='bold',\n        y=0.98,\n    )\n    fig.text(\n        0.5,\n        0.93,\n        'Stage 1 encodes strain history and separates static parameters; Stage 2 assembles the equilibrium and Maxwell contributions.',\n        ha='center',\n        va='top',\n        fontsize=10,\n    )\n\n    ax1.text(0.02, 0.90, 'Stage 1: input grouping and encoding', fontsize=11, weight='bold')\n    dyn = box(ax1, 0.03, 0.63, 0.28, 0.16, 'Dynamic raw inputs\\nstrain, strain_rate, phase', fc='#e8f1fb', weight='bold')\n    static = box(ax1, 0.03, 0.34, 0.28, 0.18, 'Static inputs\\ntendon_l1, visco_g1,\\nvisco_t1, ramp_time', fc='#e8f1fb', weight='bold')\n    tendon_raw = box(ax1, 0.03, 0.10, 0.28, 0.12, 'Raw tendon_l1', fc='#fff2cc', weight='bold')\n\n    split = box(ax1, 0.42, 0.34, 0.28, 0.18, 'Split static inputs into\\nelastic / viscous /\\nprotocol groups', fc='#f4ecff', weight='bold')\n    elastic_enc = box(ax1, 0.79, 0.63, 0.18, 0.13, 'Elastic\\nencoder', fc='#f4ecff')\n    viscous_enc = box(ax1, 0.79, 0.44, 0.18, 0.13, 'Viscous\\nencoder', fc='#f4ecff')\n    protocol_enc = box(ax1, 0.79, 0.25, 0.18, 0.13, 'Protocol\\nencoder', fc='#f4ecff')\n\n    arrow(ax1, static, split)\n    arrow(ax1, split, elastic_enc, end_frac=0.50)\n    arrow(ax1, split, viscous_enc, end_frac=0.50)\n    arrow(ax1, split, protocol_enc, end_frac=0.50)\n    ax1.annotate('', xy=anchor(elastic_enc, 'left', 0.50), xytext=anchor(dyn, 'right', 0.50), arrowprops=dict(arrowstyle='->', lw=1.4, color='#333333'))\n    ax1.text(0.53, 0.72, 'raw strain sequence', ha='center', va='bottom', fontsize=9)\n    ax1.annotate('', xy=(0.78, 0.16), xytext=anchor(tendon_raw, 'right', 0.50), arrowprops=dict(arrowstyle='->', lw=1.4, color='#333333'))\n    ax1.text(0.56, 0.16, 'raw stiffness kept for explicit scaling', ha='center', va='bottom', fontsize=9)\n\n    ax2.text(0.02, 0.90, 'Stage 2: constitutive assembly and time update', fontsize=11, weight='bold')\n    elastic_head = box(ax2, 0.05, 0.63, 0.36, 0.14, 'Elastic force head\\nF_full(t) = strain × softplus(MLP)', fc='#d9ead3', fontsize=9, weight='bold')\n    maxwell_params = box(ax2, 0.05, 0.42, 0.36, 0.14, 'Partition + tau heads\\n[g_eq, g_i] and τ_i', fc='#d9ead3', fontsize=9 ,weight='bold')\n    scale_law = box(ax2, 0.05, 0.18, 0.36, 0.14, 'Explicit tendon scaling\\nscale(l1) = s0 × (l1 / l_ref)^α', fc='#fff2cc', fontsize=9, weight='bold')\n    update = box(ax2, 0.56, 0.18, 0.36, 0.14, 'Exact Maxwell update\\nq_i ← branch states / memory', fc='#fce5cd', fontsize=9, weight='bold')\n    output = box(ax2, 0.56, 0.63, 0.36, 0.14, 'Final force\\nF = scale × [g_eq F_full + Σ q_i]', fc='#cfe2f3', fontsize=9, weight='bold')\n\n    arrow(ax2, elastic_head, output)\n    arrow(ax2, maxwell_params, update)\n    arrow(ax2, elastic_head, update, start='bottom', end='top', start_frac=0.70, end_frac=0.28)\n    arrow(ax2, scale_law, output, start='top', end='bottom', start_frac=0.50, end_frac=0.48)\n    arrow(ax2, update, output, start='top', end='bottom', start_frac=0.50, end_frac=0.78)\n\n    ax2.text(0.48, 0.81, 'equilibrium term', fontsize=9, ha='center')\n    ax2.text(0.48, 0.35, 'branch weights and time constants', fontsize=9, ha='center')\n    ax2.text(0.74, 0.52, 'Maxwell overstress states', fontsize=9, ha='center')\n    ax2.text(0.48, 0.14, 'monotone stiffness scaling', fontsize=9, ha='center')\n\n    ax2.text(\n        0.50,\n        0.05,\n        'Elastic branch gives the long-time force; Maxwell branches store transient overstress that builds during the ramp and decays during hold.',\n        ha='center',\n        va='bottom',\n        fontsize=9,\n        wrap=True,\n    )\n\n    fig.tight_layout(rect=(0, 0, 1, 0.9), w_pad=1.5)\n    return fig\n\n\ndef experiment_outputs_ready(out_dir: Path) -> bool:\n    required = [\n        out_dir / 'best_model.pt',\n        out_dir / 'metrics_summary.json',\n        out_dir / 'eval_metrics.json',\n        out_dir / 'diagnostics' / 'per_sim_metrics.csv',\n        out_dir / 'diagnostics' / 'predictions.csv',\n        out_dir / 'diagnostics' / 'prediction_summary.json',\n    ]\n    return all(path.exists() for path in required)\n\n\ndef run_experiment_pipeline(config_path: str) -> None:\n    cfg = load_config(ROOT / config_path)\n    out_dir = ROOT / cfg.training.out_dir\n    if experiment_outputs_ready(out_dir) and not FORCE_RETRAIN:\n        print(f\"Reusing existing artifacts for {config_path}\")\n        return\n\n    print(f\"Rebuilding artifacts for {config_path}\")\n    run_training(cfg)\n    evaluate_checkpoint(\n        out_dir / 'best_model.pt',\n        out_path=out_dir / 'eval_metrics.json',\n    )\n    shutil.rmtree(out_dir / 'diagnostics', ignore_errors=True)\n    generate_prediction_diagnostics(\n        out_dir / 'best_model.pt',\n        out_dir=out_dir / 'diagnostics',\n    )\n\n\nfor config_path in [\n    'configs/train_baseline.yaml',\n    'configs/train_baseline_stiffness_holdout.yaml',\n    'configs/train_maxwell.yaml',\n    'configs/train_maxwell_stiffness_holdout.yaml',\n]:\n    run_experiment_pipeline(config_path)\n\n\nbaseline_interp_metrics = load_json(ROOT / 'artifacts' / 'baseline' / 'metrics_summary.json')\nbaseline_holdout_metrics = load_json(ROOT / 'artifacts' / 'baseline_stiffness_holdout' / 'metrics_summary.json')\nphysics_interp_metrics = load_json(ROOT / 'artifacts' / 'maxwell' / 'metrics_summary.json')\nphysics_holdout_metrics = load_json(ROOT / 'artifacts' / 'maxwell_stiffness_holdout' / 'metrics_summary.json')\n\nbaseline_interp_metric_rows = load_csv_rows(ROOT / 'artifacts' / 'baseline' / 'diagnostics' / 'per_sim_metrics.csv')\nbaseline_holdout_metric_rows = load_csv_rows(ROOT / 'artifacts' / 'baseline_stiffness_holdout' / 'diagnostics' / 'per_sim_metrics.csv')\nphysics_interp_metric_rows = load_csv_rows(ROOT / 'artifacts' / 'maxwell' / 'diagnostics' / 'per_sim_metrics.csv')\nphysics_holdout_metric_rows = load_csv_rows(ROOT / 'artifacts' / 'maxwell_stiffness_holdout' / 'diagnostics' / 'per_sim_metrics.csv')\n\nbaseline_interp_series = load_prediction_series(ROOT / 'artifacts' / 'baseline' / 'diagnostics' / 'predictions.csv')\nbaseline_holdout_series = load_prediction_series(ROOT / 'artifacts' / 'baseline_stiffness_holdout' / 'diagnostics' / 'predictions.csv')\nphysics_interp_series = load_prediction_series(ROOT / 'artifacts' / 'maxwell' / 'diagnostics' / 'predictions.csv')\nphysics_holdout_series = load_prediction_series(ROOT / 'artifacts' / 'maxwell_stiffness_holdout' / 'diagnostics' / 'predictions.csv')\n\nbaseline_holdout_physics_val = physical_summary(baseline_holdout_metric_rows, baseline_holdout_series, 'val')\nbaseline_holdout_physics_test = physical_summary(baseline_holdout_metric_rows, baseline_holdout_series, 'test')\nphysics_holdout_physics_val = physical_summary(physics_holdout_metric_rows, physics_holdout_series, 'val')\nphysics_holdout_physics_test = physical_summary(physics_holdout_metric_rows, physics_holdout_series, 'test')\n\nbaseline_benchmark = benchmark_model(\n    'artifacts/baseline/best_model.pt',\n    'configs/train_baseline.yaml',\n)\nphysics_benchmark = benchmark_model(\n    'artifacts/maxwell/best_model.pt',\n    'configs/train_maxwell.yaml',\n)\n\nphysics_holdout_best, physics_holdout_worst = select_best_and_worst(physics_holdout_metric_rows, 'test')\ncomparison_sim_ids = [physics_holdout_best['sim_id'], physics_holdout_worst['sim_id']]\nbaseline_holdout_lookup = metric_lookup(baseline_holdout_metric_rows)\nphysics_holdout_lookup = metric_lookup(physics_holdout_metric_rows)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n```\nReusing existing artifacts for configs/train_baseline.yaml\nReusing existing artifacts for configs/train_baseline_stiffness_holdout.yaml\nReusing existing artifacts for configs/train_maxwell.yaml\nReusing existing artifacts for configs/train_maxwell_stiffness_holdout.yaml\n```\n:::\n:::\n\n\n:::{#901c5d0c .cell .markdown}\n## Problem Definition\n\nThis project studies force prediction for a tendon-like strip undergoing ramp-hold uniaxial extension. The underlying FEBio model uses a tendon elastic response wrapped by an uncoupled viscoelastic material, so the effective constitutive behavior is nonlinear and time dependent [@febioTheory411]. Rather than predicting full finite-element fields, the surrogate targets the global reaction force history $F(t)$, which is the quantity needed for reduced musculoskeletal simulation.\n\nFollowing the FEBio Theory Manual [@febioTheory411], the generator is motivated by transient solid mechanics with additive elastic and viscous stress contributions,\n\n$$\n\\rho \\ddot{\\mathbf{u}} = \\nabla \\cdot \\boldsymbol{\\sigma} + \\rho \\mathbf{b},\n\\qquad\n\\boldsymbol{\\sigma} = \\boldsymbol{\\sigma}_e + \\boldsymbol{\\sigma}_v,\n$$\n\nbut the learned surrogate ultimately approximates only the reduced global force response rather than the full displacement or stress field.\n\nThe final data-generation setup was a fixed-geometry tensile test:\n\n- rectangular strip: 10 mm × 2 mm × 1 mm,\n- loading axis: x,\n- target displacement: 0.5 mm,\n- target strain: 0.05,\n- total time: 1.0 s,\n- fixed output grid: 201 time points.\n\n## Data\n\nSynthetic trajectories were generated in FEBio [@febioTheory411] by varying the four parameters most closely tied to the proposal goals:\n\n- fiber stiffness: `tendon_l1 ∈ {3.0, 4.0, 5.0, 6.0}`\n- viscoelastic amplitude: `visco_g1 ∈ {0.30, 0.45, 0.60, 0.75}`\n- relaxation time: `visco_t1 ∈ {0.10, 0.20, 0.30, 0.40}`\n- loading rate: `ramp_time ∈ {0.10, 0.20, 0.30, 0.40}`\n\nA 4 × 4 × 4 × 4 design produced 256 planned simulations. Of these, 240 validated successfully after processing and QC. The 16 failures were localized to the numerically difficult corner with highest stiffness and fastest loading (`tendon_l1 = 6.0`, `ramp_time = 0.1`). All validated runs were resampled onto the same 201-point time grid to produce a model-ready dataset.\n:::\n\n::: {.cell execution_count=2}\n``` {.python .cell-code .hidden}\nplot_dataset_trajectories(ROOT / 'data' / 'processed' / 'full_sweep_v2' / 'resampled_dataset_stiffness_holdout.parquet')\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n![Validated force-time trajectories grouped by stiffness level. The systematic increase in peak and hold force with increasing tendon_l1 makes the stiffness-holdout split a meaningful extrapolation test.](report_files/figure-pdf/cell-3-output-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n:::{#71113b8c .cell .markdown}\n## Method\n\nThe learning problem is a sequence-to-sequence surrogate rather than a full field predictor. Each trajectory is represented by:\n\n- dynamic inputs: `strain`, `strain_rate`, `phase`\n- static inputs: `tendon_l1`, `visco_g1`, `visco_t1`, `ramp_time`\n- target output: `force`\n\nTwo recurrent surrogate models were evaluated.\n\n### GRU baseline\n\nThe baseline uses a gated recurrent unit (GRU) sequence model [@cho2014gru] with:\n\n- an MLP encoder for the static parameters,\n- a GRU sequence model for the dynamic trajectory,\n- a readout MLP that maps recurrent hidden states to force.\n\nThis model is flexible and accurate, but it does not explicitly enforce constitutive structure beyond recurrence.\n\n### Physics-aware coupled Maxwell model with explicit tendon scaling\n\nThe final physics-aware model is not a literal PARCv2 implementation. Instead, it is a PARC-inspired constitutive recurrent surrogate that borrows the idea of structured state evolution from PARCv2 [@nguyen2024parcv2] while using the classical generalized Maxwell picture as its viscoelastic inductive bias [@christensen1982viscoelasticity]. In a generalized Maxwell model, an equilibrium branch carries the long-time elastic response, while several parallel Maxwell branches contribute transient overstress terms that decay with their own characteristic relaxation times during a strain hold [@christensen1982viscoelasticity]. The model therefore structures the dynamics as a generalized Maxwell-style tendon surrogate:\n\n- a learned elastic force scale driven by strain history,\n- transient Maxwell overstress branches that build during the ramp and decay during hold,\n- exact enforcement of $F(0) = 0$,\n- an explicit monotone tendon stiffness scaling law applied using the raw stiffness parameter,\n\n  $$\n  s(\\mathrm{tendon\\_l1}) = s_0 \\left(\\frac{\\mathrm{tendon\\_l1}}{l_{\\mathrm{ref}}}\\right)^{\\alpha},\n  \\qquad s_0 > 0, \\; \\alpha > 0.\n  $$\n\nThis explicit scaling was introduced after simpler learned calibrators still underpredicted the force level on unseen stiffness values. It gives the model a direct, physically meaningful mechanism for increasing force with tendon stiffness. In reduced constitutive form, the final surrogate assumes\n\n$$\nF(t) = s(\\mathrm{tendon\\_l1})\\left[g_{\\mathrm{eq}} F_{\\mathrm{full}}\\!\\left(\\varepsilon(t); \\theta_e\\right) + \\sum_i q_i(t)\\right],\n$$\n\n$$\n\\frac{dq_i}{dt} = g_i d(t) - \\frac{q_i}{\\tau_i},\n\\qquad\n d(t) = \\max\\!\\left(\\frac{dF_{\\mathrm{full}}}{dt}, 0\\right),\n$$\n\nwhere $F_{\\mathrm{full}}$ is the learned elastic force scale, $q_i$ are transient Maxwell overstress states, and $\\tau_i$ are learned relaxation times. In other words, the model approximates tendon force as an equilibrium elastic contribution plus a sum of decaying nonequilibrium branches, which is the qualitative behavior expected from a generalized Maxwell material [@christensen1982viscoelasticity]. This structure makes stress relaxation during a strain hold explicit rather than leaving it entirely to a generic recurrent hidden state.\n:::\n\n::: {.cell execution_count=3}\n``` {.python .cell-code .hidden}\nplot_final_model_architecture()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n![Architecture of the final physics-aware model. Small neural subnetworks encode static parameter groups and estimate elastic/viscous quantities, while explicit Maxwell branch states carry the viscoelastic memory over time.](report_files/figure-pdf/cell-4-output-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n:::{#89e3a74b .cell .markdown}\nBoth models were trained with mean-squared error loss. Two evaluation protocols were used:\n\n1. **Interpolation split**: mixed train/val/test assignment across the parameter grid (168 / 36 / 36 simulations).\n2. **Stiffness holdout split**: whole stiffness levels held out,\n   - train: `tendon_l1 ∈ {3.0, 4.0}`\n   - val: `tendon_l1 = 5.0`\n   - test: `tendon_l1 = 6.0`\n\nThe second split is intentionally harder and probes extrapolation to unseen stiffness levels.\n\n## Results\n\n### Quantitative summary\n:::\n\n``` {.python .cell-code .hidden}\nsummary_table = make_markdown_table(\n    ['Model', 'Evaluation setting', 'Train MAE', 'Val MAE', 'Test MAE', 'Val MSE', 'Test MSE'],\n    [\n        [\n            'GRU baseline',\n            'Interpolation split',\n            f\"{baseline_interp_metrics['metrics']['train']['mae']:.5f}\",\n            f\"{baseline_interp_metrics['metrics']['val']['mae']:.5f}\",\n            f\"{baseline_interp_metrics['metrics']['test']['mae']:.5f}\",\n            f\"{baseline_interp_metrics['metrics']['val']['mse']:.2e}\",\n            f\"{baseline_interp_metrics['metrics']['test']['mse']:.2e}\",\n        ],\n        [\n            'Explicit Maxwell model',\n            'Interpolation split',\n            f\"{physics_interp_metrics['metrics']['train']['mae']:.5f}\",\n            f\"{physics_interp_metrics['metrics']['val']['mae']:.5f}\",\n            f\"{physics_interp_metrics['metrics']['test']['mae']:.5f}\",\n            f\"{physics_interp_metrics['metrics']['val']['mse']:.2e}\",\n            f\"{physics_interp_metrics['metrics']['test']['mse']:.2e}\",\n        ],\n        [\n            'GRU baseline',\n            'Stiffness holdout',\n            f\"{baseline_holdout_metrics['metrics']['train']['mae']:.5f}\",\n            f\"{baseline_holdout_metrics['metrics']['val']['mae']:.5f}\",\n            f\"{baseline_holdout_metrics['metrics']['test']['mae']:.5f}\",\n            f\"{baseline_holdout_metrics['metrics']['val']['mse']:.2e}\",\n            f\"{baseline_holdout_metrics['metrics']['test']['mse']:.2e}\",\n        ],\n        [\n            'Explicit Maxwell model',\n            'Stiffness holdout',\n            f\"{physics_holdout_metrics['metrics']['train']['mae']:.5f}\",\n            f\"{physics_holdout_metrics['metrics']['val']['mae']:.5f}\",\n            f\"{physics_holdout_metrics['metrics']['test']['mae']:.5f}\",\n            f\"{physics_holdout_metrics['metrics']['val']['mse']:.2e}\",\n            f\"{physics_holdout_metrics['metrics']['test']['mse']:.2e}\",\n        ],\n    ],\n)\nprint(summary_table)\n```\n| Model | Evaluation setting | Train MAE | Val MAE | Test MAE | Val MSE | Test MSE |\n| --- | --- | --- | --- | --- | --- | --- |\n| GRU baseline | Interpolation split | 0.00710 | 0.00644 | 0.00818 | 6.85e-05 | 1.06e-04 |\n| Explicit Maxwell model | Interpolation split | 0.00861 | 0.00834 | 0.00831 | 1.15e-04 | 1.10e-04 |\n| GRU baseline | Stiffness holdout | 0.01643 | 0.06507 | 0.16790 | 6.33e-03 | 4.10e-02 |\n| Explicit Maxwell model | Stiffness holdout | 0.01018 | 0.02466 | 0.04947 | 9.64e-04 | 3.21e-03 |\n\n\n:::{#a120a9f5 .cell .markdown}\nThe GRU baseline remains an excellent interpolation model, but the new explicit-tendon-scaling Maxwell surrogate is now nearly tied with it on the interpolation test set (0\\.00831 vs. 0\\.00818 test MAE). The much more important result is on the stiffness-holdout benchmark: the explicit Maxwell model reduces holdout MAE from 0\\.0651 to 0\\.0247 on validation and from 0\\.1679 to 0\\.0495 on test. This is about a 71% reduction in test MAE while simultaneously improving physical plausibility.\n\n### Computational cost\n:::\n\n``` {.python .cell-code .hidden}\nspeed_table = make_markdown_table(\n    ['Model', 'Parameter count', 'CPU ms / batch', 'CPU ms / simulation'],\n    [\n        ['GRU baseline', f\"{baseline_benchmark['n_params']:,}\", f\"{baseline_benchmark['ms_per_batch']:.2f}\", f\"{baseline_benchmark['ms_per_sim']:.3f}\"],\n        ['Explicit Maxwell model', f\"{physics_benchmark['n_params']:,}\", f\"{physics_benchmark['ms_per_batch']:.2f}\", f\"{physics_benchmark['ms_per_sim']:.3f}\"],\n    ],\n)\nprint(speed_table)\n```\n| Model | Parameter count | CPU ms / batch | CPU ms / simulation |\n| --- | --- | --- | --- |\n| GRU baseline | 56,065 | 9.93 | 0.621 |\n| Explicit Maxwell model | 20,748 | 20.01 | 1.251 |\n\n\n:::{#b6ed843e .cell .markdown}\nBoth surrogate models are lightweight compared with the FEBio generator. The GRU baseline has more trainable parameters because it carries a 2-layer recurrent hidden state, while the explicit Maxwell model replaces that generic recurrence with four explicit viscoelastic modes and a few small MLP heads. The timing numbers above were measured on CPU in the report execution environment and are intended as relative complexity indicators rather than a hardware-optimized benchmark.\n:::\n\n::: {.cell execution_count=6}\n``` {.python .cell-code .hidden}\nplot_model_metric_comparison(\n    baseline_interp_metrics,\n    physics_interp_metrics,\n    baseline_holdout_metrics,\n    physics_holdout_metrics,\n)\n```\n:::\n\n\n:::{#4cec5367 .cell .markdown}\n### Interpolation split diagnostics\n\nOn the interpolation split, the explicit Maxwell model still captures the full ramp-hold behavior well, so the stronger holdout performance is not a tradeoff against in-range accuracy. The model remains physically plausible on nearby parameter combinations, including near-zero force at the start of loading, while matching the baseline test error closely.\n\n### Stiffness-holdout diagnostics\n\nThe stiffness-holdout benchmark is the clearest discriminator between the two models. The GRU baseline develops a nonphysical force offset at `t = 0` and substantially underpredicts the force level on unseen `tendon_l1 = 6.0` trajectories. In contrast, the explicit Maxwell model preserves realistic relaxation during hold, maintains exact `F(0) = 0`, and substantially reduces the force-scale bias.\n:::\n\n``` {.python .cell-code .hidden}\nholdout_physics_table = make_markdown_table(\n    ['Model', 'Split', 'Mean predicted F(0)', 'Mean predicted relaxation', 'Mean true relaxation', 'Mean abs. relaxation error'],\n    [\n        [\n            'GRU baseline',\n            'Validation',\n            f\"{baseline_holdout_physics_val['mean_t0_pred']:.4f}\",\n            f\"{baseline_holdout_physics_val['mean_pred_relax']:.4f}\",\n            f\"{baseline_holdout_physics_val['mean_true_relax']:.4f}\",\n            f\"{baseline_holdout_physics_val['mean_abs_relax_err']:.4f}\",\n        ],\n        [\n            'Explicit Maxwell model',\n            'Validation',\n            f\"{physics_holdout_physics_val['mean_t0_pred']:.4f}\",\n            f\"{physics_holdout_physics_val['mean_pred_relax']:.4f}\",\n            f\"{physics_holdout_physics_val['mean_true_relax']:.4f}\",\n            f\"{physics_holdout_physics_val['mean_abs_relax_err']:.4f}\",\n        ],\n        [\n            'GRU baseline',\n            'Test',\n            f\"{baseline_holdout_physics_test['mean_t0_pred']:.4f}\",\n            f\"{baseline_holdout_physics_test['mean_pred_relax']:.4f}\",\n            f\"{baseline_holdout_physics_test['mean_true_relax']:.4f}\",\n            f\"{baseline_holdout_physics_test['mean_abs_relax_err']:.4f}\",\n        ],\n        [\n            'Explicit Maxwell model',\n            'Test',\n            f\"{physics_holdout_physics_test['mean_t0_pred']:.4f}\",\n            f\"{physics_holdout_physics_test['mean_pred_relax']:.4f}\",\n            f\"{physics_holdout_physics_test['mean_true_relax']:.4f}\",\n            f\"{physics_holdout_physics_test['mean_abs_relax_err']:.4f}\",\n        ],\n    ],\n)\nprint(holdout_physics_table)\n```\n| Model | Split | Mean predicted F(0) | Mean predicted relaxation | Mean true relaxation | Mean abs. relaxation error |\n| --- | --- | --- | --- | --- | --- |\n| GRU baseline | Validation | 0.2216 | 0.3173 | 0.3649 | 0.0580 |\n| Explicit Maxwell model | Validation | 0.0000 | 0.3657 | 0.3649 | 0.0104 |\n| GRU baseline | Test | 0.3396 | 0.2989 | 0.3390 | 0.0624 |\n| Explicit Maxwell model | Test | 0.0000 | 0.3443 | 0.3390 | 0.0109 |\n\n\n:::{#3c770ddd .cell .markdown}\nThe table above highlights the main physical improvement. On the holdout test set, the GRU predicts a mean initial force of 0\\.3396, while the explicit Maxwell model predicts exactly 0\\.0. The explicit Maxwell model also matches the mean relaxation ratio much more closely (0\\.3443 predicted vs. 0\\.3390 true) than the GRU (0\\.2989 predicted).\n:::\n\n::: {.cell execution_count=8}\n``` {.python .cell-code .hidden}\nplot_case_comparison(\n    comparison_sim_ids,\n    baseline_holdout_series,\n    physics_holdout_series,\n    baseline_holdout_lookup,\n    physics_holdout_lookup,\n    'Stiffness-holdout trajectory comparison',\n)\n```\n:::\n\n\n:::{#51cc1a97 .cell .markdown}\nEven on the hardest holdout case (full\\_v2\\_206), the explicit Maxwell model lowers the error dramatically and maintains the correct qualitative shape. The remaining discrepancy is mostly a modest residual underprediction of the force level, not a breakdown of the constitutive behavior itself.\n\n## Conclusion\n\nThe FEBio pipeline successfully produced a high-quality dataset of validated tendon force trajectories, and the modeling study now gives a clear comparison between a strong generic recurrent baseline and a more physically structured constitutive surrogate.\n\nThe main findings are:\n\n- The GRU baseline is an excellent interpolation model on this smooth, fixed-protocol sequence dataset.\n- A generalized Maxwell-style recurrent model with explicit tendon stiffness scaling can nearly match the GRU on interpolation.\n- On the harder stiffness-holdout benchmark, the explicit Maxwell model is substantially better than the GRU baseline.\n- The explicit Maxwell model enforces `F(0) = 0` exactly and reproduces hold-phase relaxation much more faithfully under extrapolation.\n- The remaining holdout error is mainly a reduced force-level bias, not a failure to capture the viscoelastic relaxation mechanism.\n\nOverall, the final project supports the central hypothesis that adding constitutive structure and physically meaningful parameter scaling can materially improve out-of-distribution generalization, even when a less structured recurrent model is already strong on interpolation.\n\nFuture work should focus on three directions. First, the present explicit-Maxwell surrogate could be extended toward a more faithful differentiator–integrator PARCv2-style training procedure, separating learned rate-law estimation from correction/integration. Second, the data space could be broadened by adding more stiffness levels, additional loading protocols, and possibly simple geometric variations to probe generalization beyond the current ramp-hold strip test. Third, a more explicit timing comparison against FEBio would strengthen the case for surrogate deployment in larger multiscale or musculoskeletal simulations.\n\n\n## References\n:::\n\n",
    "supporting": [
      "report_files/figure-pdf"
    ],
    "filters": [],
    "includes": {}
  }
}